eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      registryFetchIntervalSeconds: 5
      
spring:
  application:
    name: cadastro-clientes
  datasource:
    url: jdbc:mysql://localhost:3306/cadastro?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest      
