eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
      registryFetchIntervalSeconds: 5
server:
  port: ${PORT:8200}
spring:
  application:
    name: clientes
  datasource:
    url: jdbc:mysql://basemysql:3306/cadastro?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  
management:
  endpoints:
    web:
      exposure:
        include: "*"    
