eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      registryFetchIntervalSeconds: 5
      
server:
  port: 9091
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/curso
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest 
    
management:
  endpoints:
    web:
      exposure:
        include: "*"    


---
spring.profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka/eureka
      registryFetchIntervalSeconds: 5
      
server:
  port: 9091
spring:
  rabbitmq:
    host: rabbitmq
  data:
    mongodb:
      uri: mongodb://mongo/curso      
