eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
      registryFetchIntervalSeconds: 5
      
server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/curso
  datasource:
    url: jdbc:mysql://basemysql:3306/cadastro?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest   
